CREATE DATABASE db;
USE db;
#tabelas do banco
/*
 COMENTÁRIO DO JHON:
 LEMBRETE PARA O MOMENTO DA CRIAÇÃO DAS TABELAS VIA BACK-END:
-- ENCONTRAR UM COMANDO PARA ACIONAR A CRIAÇÃO ATOMATICAS DAS TABELAS NA ORDEM:
--> USUÁRIO -> ESTOQUE -> PRODUTO -> ESTQOUE_PRODUTO -> MOVIMENTACAO -> PEDIDO_ENTREGA;
*/
		#TABELA USUARIO
create table IF NOT EXISTS USUARIO(
	ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY NOT NULL, 
    EMAIL_USUARIO VARCHAR(255) NOT NULL UNIQUE,
    SENHA_USUARIO VARCHAR(255) NOT NULL,
    DATA_CADASTRO DATE DEFAULT NULL,
    DATA_ATUALIZACAO DATE DEFAULT NULL,
    CONSTRAINT CHK_SENHA_TAMANHO CHECK (LENGTH(SENHA_USUARIO) >= 3)
);

       #TABELA ESTOQUE
create table IF NOT EXISTS ESTOQUE(
	ID_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
--	#NÃO SEI SE PODIA TER UM ATRIBUTO: "TIPO_ESTOQUE", MAS ACHO Q FARIA MAIS SENTIDO
	CATEGORIA_ESTOQUE ENUM('Alimentos', 'Bebidas', 'Laticínios') NOT NULL,
	QTDE_ESTOQUE INT
);

		#TABELA PRODUTO
CREATE TABLE IF NOT EXISTS PRODUTOS(
	    ID_PRODUTO INT AUTO_INCREMENT PRIMARY key,
        NOME_PRODUTO VARCHAR(255) NOT NULL UNIQUE,
        PRECO_PRODUTO FLOAT NOT NULL,
        FK_ID_ESTOQUE INT DEFAULT NULL,
	    DESC_PRODUTO VARCHAR(255) NULL,
        NUMERO_NF_PRODUTO VARCHAR(255) NULL UNIQUE,
        VALIDADE_PRODUTO DATE NOT NULL,
        FORNECEDOR_PRODUTO VARCHAR(255) NULL,
        QTD_MINIMA_PRODUTO INT NOT NULL,
        FOREIGN KEY (FK_ID_ESTOQUE) REFERENCES ESTOQUE(ID_ESTOQUE) ON DELETE SET NULL
        ); 
/*obs: Não sei se devia ter um parametro do tipo: código de barra, já que ele tem um metodo chamado: "cadastra_via_nota_discal, eu acho?"
	Não adicionei pq n tava no diagrama, mas dá pra alterar
*/


		#TABELA MOVIMENTACAO
CREATE TABLE IF NOT EXISTS MOVIMENTACAO(
	ID_MOVIMENTACAO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	FK_ID_PRODUTO INT NOT NULL,
    QTDE INT NOT NULL, 
    TIPO_MOVIMENTACAO VARCHAR(255) NOT NULL,
    DATA_MOVIMENTACAO DATE NOT NULL,
    FOREIGN KEY (FK_ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

	#TABELA ATIVIDADES
CREATE TABLE atividades (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR(50) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    QUANTIDADE INT DEFAULT 0,
    DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP
);
 
#ESTOQUE
INSERT INTO ESTOQUE(TIPO_ESTOQUE, LISTAPRODUTOS) #CASO ESCOLHA ADICIONAR A COLUNA TIPO_PRODUTO TIPO_PRODUTO 
VALUES ("FRUTA", '["MAÇÃ", "BANANA", "UVA"]');
INSERT INTO ESTOQUE(TIPO_ESTOQUE, LISTAPRODUTOS) #CASO ESCOLHA ADICIONAR A COLUNA TIPO_PRODUTO TIPO_PRODUTO 
VALUES ("ELETRÔNICOS", '["CELL_1", "CELL_2", "CELL_3"]');
INSERT INTO ESTOQUE(TIPO_ESTOQUE, LISTAPRODUTOS) #CASO ESCOLHA ADICIONAR A COLUNA TIPO_PRODUTO TIPO_PRODUTO 
VALUES ("MATERIAL DE CONSTRUÇÃO", '["CIMENTO", "AREIA", "MACACO"]');
INSERT INTO ESTOQUE(TIPO_ESTOQUE, LISTAPRODUTOS) #CASO ESCOLHA ADICIONAR A COLUNA TIPO_PRODUTO TIPO_PRODUTO 
VALUES ("SUCOS", '["MAÇÃ", "BANANA", "UVA"]');


#PRODUTO
INSERT INTO PRODUTO(NOME_PRODUTO, PRECO_PRODUTO, FK_ID_ESTOQUE_PRODUTO, DESC_PRODUTO, NUMERO_NF_PRODUTO, VALIDADE_PRODUTO, FORNECEDOR_PRODUTO)
VALUES ("MAÇÃ", 10.20, 1, "BELA MAÇÃ VERDE, EXCELENTE PARA DIARREIA");
INSERT INTO PRODUTO(NOME_PRODUTO, PRECO_PRODUTO, FK_ID_ESTOQUE_PRODUTO, DESC_PRODUTO, NUMERO_NF_PRODUTO, VALIDADE_PRODUTO, FORNECEDOR_PRODUTO)
VALUES ("IPHONE 22", 100000, 2, "EXCELENTE PARA CLASSE MÉDIA ALTA");
INSERT INTO PRODUTO(NOME_PRODUTO, PRECO_PRODUTO, FK_ID_ESTOQUE_PRODUTO, DESC_PRODUTO, NUMERO_NF_PRODUTO, VALIDADE_PRODUTO, FORNECEDOR_PRODUTO)
VALUES ("CIMENTO", 100, 3, "EXCELENTE PARA CONSTRUIR A BOCA");

#ESTOQUE_PRODUTO

INSERT INTO ESTOQUE_PRODUTO(FK_ID_ESTOQUE, FK_ID_PRODUTO, QTDE)
VALUES (1, 1, 500);
INSERT INTO ESTOQUE_PRODUTO(FK_ID_ESTOQUE, FK_ID_PRODUTO, QTDE)
VALUES (1, 1, 900);
INSERT INTO ESTOQUE_PRODUTO(FK_ID_ESTOQUE, FK_ID_PRODUTO, QTDE)
VALUES (2, 2, 600);
INSERT INTO ESTOQUE_PRODUTO(FK_ID_ESTOQUE, FK_ID_PRODUTO, QTDE)
VALUES (2, 2, 1500);


#MOVIMENTACA

INSERT INTO MOVIMENTACAO(FK_ID_PRODUTO, QTDE, TIPO_MOVIMENTACAO, DATA_MOVIMENTACAO)
VALUES(3, 50, 'ENTRADA', '2025-04-11');
insert into MOVIMENTACAO(FK_ID_PRODUTO, QTDE, TIPO_MOVIMENTACAO, DATA_MOVIMENTACAO)
VALUES(1, 100, 'SAIDA', '2025-11-12' );
insert into MOVIMENTACAO(FK_ID_PRODUTO, QTDE, TIPO_MOVIMENTACAO, DATA_MOVIMENTACAO)
VALUES(2, 50, 'ENTRADA', '2025-04-11' );
insert into MOVIMENTACAO(FK_ID_PRODUTO, QTDE, TIPO_MOVIMENTACAO, DATA_MOVIMENTACAO)
VALUES(2, 50, 'ENTRADA', '2025-04-12' );


